### ISSUE TITLE
Create a side menu for options

### ISSUE THREAD

**Issue by Luigi1992** [Luigi1992/quick-study#40]
For a better look and fell, we have to create a side menu, like the one in Google Play Store.

![google-play-store-5-4-xxx-710x1262](https://cloud.githubusercontent.com/assets/6882024/6246112/a7dcd0de-b765-11e4-91cf-ab45115da21c.jpeg)

**Comment by alessio-balda** [comment]
Ok, but what are we going to put in this menu? We don't have that many options

**Comment by Luigi1992** [comment]
I know, we have essentially this options to put:
- Help and feedback
- About the application
- Tutorial
- Settings

Maybe they are few for this type of menu, but they are also too many for the classic drop-down menu. Isn't it?

**Comment by alessio-balda** [comment]
Maybe we could just put "About the application" and "Tutorial"  inside of "Help and feedback"

**Comment by Luigi1992** [comment]
Yes,you are right. Maybe we should do this if we have some extra time in the end.

**Comment by alessio-balda** [comment]
Done. If you want to, you can change the image at the top
