### ISSUE TITLE
Study session is not created for the day before the exam

### ISSUE THREAD

**Issue by alessio-balda** [Luigi1992/quick-study#46]

**Comment by Luigi1992** [comment]
Yes, this happen if the exam is in the morning. I thought to solve it, but I think that we can leave as it is, because the day before the exam we surely do exercise the whole day and maybe the user won't follow our scheduling anyway. What do you think of it?

**Comment by alessio-balda** [comment]
If you put it that way it might work. But I think we need to tell the user about it

**Comment by Luigi1992** [comment]
Yes, maybe in the tutorial or in another way, but we should inform the user.

**Comment by Luigi1992** [comment]
Now the exam is created the day before the exam and the day of the exam if the exam is in the afternoon.
